### ISSUE TITLE
Symbol is not defined

### ISSUE THREAD

**Issue by EisenbergEffect** [YoloDev/babel-dts-generator#1]
I was trying this out for the first time finally by adding it into the build process of one of Aurelia's libraries. Unfortunately, I get a "Symbol is not defined" error. It seems that the plugin's transpiled code is expecting some ES6-related polyfills to be present, which are not.

Any chance you have time to look into this soon? I think I'd really like to use it for Aurelia's d.ts support.

**Comment by EisenbergEffect** [comment]
I've confirmed that if I manually convert the transpiled code to not use Symbols and to use standard for loops instead, everything works. Do you think there's some configuration I'm missing? or did Babel change?

**Comment by Alxandr** [comment]
Not sure. Will look at it tomorrow.

##  --

Alxandr

**Comment by Alxandr** [comment]
So, I just did a clean fork of Alxandr/dependency-injection (branch feature-dts), ran `gulp build`, and it just works. Not sure what's different between your setup and mine, do you have everything up to date?

**Comment by EisenbergEffect** [comment]
I was applying this manually to another library. I literally updated the gulp-babel task two days ago and I thought I followed your code exactly.

**Comment by Alxandr** [comment]
Can you verify that doing a clean fork of the Alxandr/dependency-injection, running `npm install` followed by `gulp build` works for starter?

**Comment by EisenbergEffect** [comment]
I have verified that it does not work. I receive the same "Symbol is not defined" error. Switching the for/of loops to standard for loops does solve this problem.

**Comment by Alxandr** [comment]
Hmm. Weird. It works on my machine. I'll set up some travis tests to see if it's based on node version or similar. Btw, could you check your node version?

**Comment by EisenbergEffect** [comment]
Looks like I've got 0.10.30. That seems a bit old. Let me try updating and see if that changes things.

**Comment by EisenbergEffect** [comment]
Bingo! It was my  node version. I'll close this issue. Good call. I hadn't realized how far behind I was. Now, that leaves the interface issue.
