### ISSUE TITLE
Optional Parameters in Class Instance Methods

### ISSUE THREAD

**Issue by EisenbergEffect** [YoloDev/babel-dts-generator#14]
It appears that the  `?` is being dropped when generating the d.ts for class instance members. It works fine for static methods and interfaces from what I can tell, but not instance methods. Some constructors work but some do not. I'm not sure why.

As an example, you can look at aurelia/dependency-injection. The container class's constructor and methods to not have optional params generated. But you can see that the Optional resolver's constructor works fine.

**Comment by cmichaelgraham** [comment]
@Alxandr feel free to assign to me if you like...

**Comment by cmichaelgraham** [comment]
this can be closed now :+1:
