### ISSUE TITLE
complex union types changed on output to .d.ts

### ISSUE THREAD

**Issue by cmichaelgraham** [YoloDev/babel-dts-generator#17]
referencing https://github.com/aurelia/router/pull/145
@Alxandr - feel free to assign to me

The build process translates the union type into the d.ts incorrectly:

```
//router.js
configure(callbackOrConfig:RouterConfiguration|((config:RouterConfiguration) => RouterConfiguration)):Router {`
```

```
//.d.ts files
configure(callbackOrConfig: RouterConfiguration | (config: RouterConfiguration) => RouterConfiguration): Router;
```

The parentheses around `((config:RouterConfiguration) => RouterConfiguration))` are lost when writing the `d.ts` file. 

This is causing errors, not during build but when using the typescript compiler:

```
jspm_packages\github\JeroenVinke\router@master\index.d.ts(131,62): error TS1005: ')' expected. jspm_packages\github\JeroenVinke\router@master\index.d.ts(131,85): error TS1144: '{' or ';' expected. jspm_packages\github\JeroenVinke\router@master\index.d.ts(131,107): error TS1005: ';' expected. jspm_packages\github\JeroenVinke\router@master\index.d.ts(131,108): error TS1068: Unexpected token. A constructor, method, accessor, or property was expected. 
```

ping @EisenbergEffect, @JeroenVinke

**Comment by Alxandr** [comment]
Ouch. Yeah, that's rather icky. Can we (to simplify) just add parenthesises around any union case (is that still valid)?

**Comment by cmichaelgraham** [comment]
this can be closed now :+1:
