### ISSUE TITLE
suppress function, var and class exports matching `ignoreMembers`

### ISSUE THREAD

**Issue by cmichaelgraham** [YoloDev/babel-dts-generator#19]
library authors desire a mechanism to identify and suppress module exports that are not desired to be part of the library's public API

**Comment by Alxandr** [comment]
Isn't this handled by #15?

**Comment by cmichaelgraham** [comment]
same idea, but #15 doesn't filter var exports or class exports

**Comment by cmichaelgraham** [comment]
this can be closed now :+1:
