### ISSUE TITLE
Interfaces

### ISSUE THREAD

**Issue by EisenbergEffect** [YoloDev/babel-dts-generator#2]
Babel can ignore interfaces, which is great. But, if you try to export an interface, it fails. Also, interfaces, in either case (exported or not) do not get included in generated d.ts files, which makes it difficult to represent the API of many libraries.

Could the transformer be updated to prevent the Babel failure and also include the interfaces in the d.ts files?

**Comment by Alxandr** [comment]
Yeah, sure. This should be fairly straight forward. It was just that there were no interfaces in the sample repository I used (dependency-injection).

**Comment by EisenbergEffect** [comment]
That would be cool :)

**Comment by EisenbergEffect** [comment]
Ok. I've pushed a branch with my experiement: https://github.com/aurelia/route-recognizer/commits/dts-experiment

This errors our during compile due to the Symbol issue I mentioned in #1 In addition to that, the interfaces are not represented in the resulting d.ts file. If you add export in front of the interfaces, it also errors.

As a final item, I don't get the ambient module declaration I want. Perhaps an override for the config that will let me specify that exactly, would work.

**Comment by EisenbergEffect** [comment]
I saw a post in the gitter channel, but was curious how close you think you are to getting this working.

**Comment by Alxandr** [comment]
Yeah, I can get it working. I have indexes working already `interface Foo { [bar: number]: string }`, however, I don't have too much time given work. I will probably be able to get it done within a few days though. Unless I run into any major issues, I can promise to **at least** have it done by the end of the work-week.

**Comment by Alxandr** [comment]
Oh, and (for now) at least, due to time constraints, and a bunch of other work I'm doing, I'm not enabling generics in most of it. It can be fitted in in places where it's needed fairly easy, but it's really painful having to manually figure out the AST (the non-ES parts of it aren't documented).

**Comment by Alxandr** [comment]
Release 0.2.1 (up on NPM) supports interfaces.
