### ISSUE TITLE
Exported Objects Types are Stripped

### ISSUE THREAD

**Issue by EisenbergEffect** [YoloDev/babel-dts-generator#24]
The following code:

```
export let Metadata : MetadataType = { ... }
```

Becomes this:

```
export var Metadata: any;
```

The type information is replaced with `any`.

**Comment by EisenbergEffect** [comment]
@cmichaelgraham This issue also comes from our Metadata repo.

**Comment by Alxandr** [comment]
This has been solved. Can't remember when.
