### ISSUE TITLE
ObjectTypeCallProperty not supported.

### ISSUE THREAD

**Issue by EisenbergEffect** [YoloDev/babel-dts-generator#25]
Consider the following interface;

```
interface XHRTransformer {
  (client : HttpClient, processor : RequestMessageProcessor, message : RequestMessage, xhr : XHR) : void;
}
```

ObjectTypeCallProperty not supported is emitted from the generator when this code is present.

**Comment by EisenbergEffect** [comment]
@cmichaelgraham Here's another one for you. This relates to the HttpClient repo.

**Comment by Alxandr** [comment]
@EisenbergEffect this was actually intentionally not supported at the beginning. The point was that this isn't really a interface. It's just you wanting to name a function (like a .NET delegate). Though, not saying I'm against adding it, just saying you could just as well use a function.

**Comment by EisenbergEffect** [comment]
It is valid TypeScript, which is why I came across the issue.

**Comment by Alxandr** [comment]
Yeah, I know very well it's valid typescript. But it's a part of typescript that's generally just made to be able to describe strange libraries that already existed, and did not conform to the way of typescript :P (at least that was my understanding of it), thus I didn't support it.
