### ISSUE TITLE
typeof Class type annotation not supported

### ISSUE THREAD

**Issue by davismj** [YoloDev/babel-dts-generator#54]
The `typeof Class` annotation is not supported. I double checked and this is a valid typing (see [constructor functions](https://www.typescriptlang.org/docs/handbook/classes.html#constructor-functions)).

``` typescript
myFunction(class: typeof SomeClass): {}
```

>  Error: path/to/code.ts: Unsupported type annotation type: TypeofTypeAnnotation

**Comment by Alxandr** [comment]
Does babel support this? Babel only supports a subset of TypeScript (through flow). It's impossible to support anything babel doesn't until I can extend the parser.

**Comment by davismj** [comment]
I'm not sure if Babel supports it, as I couldn't find any babel/flow docs, but Flow supports this.

https://flowtype.org/docs/typeof.html

**Comment by davismj** [comment]
Still getting the error, even after updating to 0.6.1.
> Error: D:/Dropbox/Work/aurelia/dialog/dist/aurelia-dialog.js: Unsupported type
annotation type: TypeofTypeAnnotation
