### ISSUE TITLE
ObjectPattern in function parameters not supported

### ISSUE THREAD

**Issue by repkins** [YoloDev/babel-dts-generator#60]
Hello!

Im trying to extract ts definitions from module with exported functions using object pattern syntax in arguments, and im getting this error on console 
```
ObjectPattern not supported.
Failed processing arguments for function UserDeleted.
```
I see its generated d.ts file but there is no such functions at all.

Can you make this working?

**Comment by Alxandr** [comment]
Please provide a minimum failing code snippet.

**Comment by repkins** [comment]
Ok, here is one:

```
export function SampleFunction({sampleName, sampleValue}) {
    this.sampleName = sampleName;
    this.sampleValue = sampleValue;
}
```

**Comment by Alxandr** [comment]
What would you expect the DTS of this to look like? Cause as far as I can tell you can't really do more than `SampleFunction(opts: any?)`.

**Comment by repkins** [comment]
Would be much better to be something like this:

```
SampleFunction(opts: {
    sampleName?: any,
    sampleValue?: any,
    // ... syntax for allowing other propeties undefined here maybe
})
```

So it would let developer know about possible properties in object argument, like possible arguments in function.

**Comment by Alxandr** [comment]
The last part is sort of troublesome. Also, this would require a rather large rewrite I think, though I'll look into it.

**Comment by Alxandr** [comment]
Turned out to be less troublesome than I thought. PR #64 should cover most use cases.
